# https://help.github.com/ja/articles/metadata-syntax-for-github-actions
name: WP Version Check Action

description: GitHub Action to check versions of wp plugin files before publish.

author: technote-space

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    required: true
  BRANCH_PREFIX:
    description: Branch name prefix.
    default: ''
    required: false
  COMMIT_DISABLED:
    description: Whether commit is disabled.
    default: ''
    required: false
  COMMIT_MESSAGE:
    description: Commit message of update package version commit.
    default: 'feat: update version'
    required: true
  TEST_TAG_PREFIX:
    description: Tag name prefix for test
    default: ''
    required: false

branding:
  icon: 'package'
  color: 'blue'

runs:
  using: node12
  main: lib/main.js
